# Start services.
start-services:
	@echo "Starting services..."
	@docker-compose up -d
	@echo "Done starting services"

# Stops services.
stop-services:
	@echo "Stopping services..."
	@docker-compose down
	@echo "Done stopping services"
